### ISSUE TITLE
Does not work with Launchpad Mini Mk2

### ISSUE THREAD

**Issue by Hellohi3654** [quaternionmedia/LaunchChess#23]
I have tried reinstalling drivers and even using a different computer and I can't get it to work
It works with Ableton's website arcade demo thingo

It says Launchpad Mini appears in the input and output dropdown boxes but the red dot never goes green no matter what I try

Also I am using Google chrome and have given launchchess.com access to midi devices in site settings.

Just wondering if there is a fix 
Thanks

**Comment by mrharpo** [comment]
Hi, @Hellohi3654! Thanks for taking the time to report an issue!

I tried to make everything compatible for all Launchpads, per the programmer's reference guide, but I don't have a Launchpad Mini to test against.

Can you provide the console logs in the developer tools?

We've had some issues in the past getting it to work with Windows.  Is it possible to try it on a mac or linux machine?

Also, try running it with administrator privilege, or possibly a different browser, such as Opera. (Firefox does not support the webmidi spec yet)

Thanks!

**Comment by Hellohi3654** [comment]
> Hi, @Hellohi3654! Thanks for taking the time to report an issue!
> 
> I tried to make everything compatible for all Launchpads, per the programmer's reference guide, but I don't have a Launchpad Mini to test against.
> 
> Can you provide the console logs in the developer tools?
> 
> We've had some issues in the past getting it to work with Windows.  Is it possible to try it on a mac or linux machine?
> 
> Also, try running it with administrator privilege, or possibly a different browser, such as Opera. (Firefox does not support the webmidi spec yet)
> 
> Thanks!

I can only test on a windows machine but I could try and run Linux if you want
I will try running as admin and also try Opera
I can also get the console logs

**Comment by mrharpo** [comment]
@Hellohi3654 Interesting... Tetrispad is not working for my Launchpad X (although it is recognized). On my Launchpad mk2 (not mini) it lights up some buttons, but the grid sequence is out of order, and is not playable.

Anyway, if you can tell me the MIDI name of the device, I can map that to use the proper bindings here. 

It should be available in an object printed to the console. It might be something like: `LPMiniMK2 MIDI In`

**Comment by Hellohi3654** [comment]
![image](https://user-images.githubusercontent.com/57390764/156948299-1dd67af8-27d2-4cba-a813-8bf470538c92.png)

**Comment by Hellohi3654** [comment]
![image](https://user-images.githubusercontent.com/57390764/156948339-9c0e2a73-3681-42ca-b9ac-4aed711a9497.png)

**Comment by Hellohi3654** [comment]
not really sure what I'm looking for

**Comment by mrharpo** [comment]
Thanks @Hellohi3654! This is just what I need. I'm just looking for the name: "Launchpad Mini".

I made the potential fix, and pushed it to our staging environment: https://magnus.quaternion.media

Let me know if it works, or if you get another error message.

**Comment by Hellohi3654** [comment]
I tried out that website it's working but that mappings are still not right buttons just seem to do random things
There are no errors in the console
Thanks

**Comment by Hellohi3654** [comment]
just wondering if there's any updates on this
thanks

**Comment by mrharpo** [comment]
Hmmm... The programmer's reference manual does not exist for this model, and this is the only model that is missing it.

If it's sending lights, but in the wrong order, it's possible it uses the older bindings.

I've made a patch (83dccfc) on https://magnus.quaternion.media/

Try it out (be sure to check the "disable cache" button in the network tab before refreshing). 

If it doesn't work, send a picture. If it does work, send a picture!

**Comment by Hellohi3654** [comment]
ok thanks I'll try it out

**Comment by Hellohi3654** [comment]
![IMG_20220611_202247.jpg](https://user-images.githubusercontent.com/57390764/173183906-44de8b6b-d0f3-4386-bf7d-71013d07a112.jpg)

Been a little while here is what shows up when I try and use the launch pad

**Comment by Hellohi3654** [comment]
![IMG_20220611_202424~2.jpg](https://user-images.githubusercontent.com/57390764/173183962-fd2e93e8-1e6d-46d0-ac2e-059819bb5d7a.jpg)

The four buttons with green are the first four pawns from left to right in the bottom left hand corner of the board

**Comment by Hellohi3654** [comment]
btw don't know if this helps but this tetris game works fine on my launchpad
https://maxwellito.github.io/tetrispad/

**Comment by mrharpo** [comment]
@Hellohi3654 I've made some fixes that might make your Launchpad work. Would you mind giving it a try again at https://magnus.quaternion.media/ and posting any output logs that happen if it doesn't work?

Thanks!

**Comment by mrharpo** [comment]
Closing, since it's been a year since the last update.

@Hellohi3654 Feel free to reopen if this is still an issue.
