### ISSUE TITLE
With my launchpad mini mk3 its not working.

### ISSUE THREAD

**Issue by Vabene0312** [quaternionmedia/LaunchChess#24]
Please help me.

Every time I push a button this error.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/74011927/212379067-35e68e7f-9caa-4c33-bd50-709052ee6acc.png">

**Comment by mrharpo** [comment]
Can you try it on https://magnus.quaternion.media/ ?

If that doesn't work, put the error message here, along with any other relevant screenshots and I'll take a look when I can.

Thanks!

**Comment by Vabene0312** [comment]
<img width="404" alt="image_1" src="https://user-images.githubusercontent.com/74011927/212407397-b66b1d67-00df-4ada-97b6-6ad8ad7d9528.png">
<img width="416" alt="image_2" src="https://user-images.githubusercontent.com/74011927/212407399-c952831d-0638-441d-b44c-1a22eb483a4c.png">
<img width="408" alt="image_3" src="https://user-images.githubusercontent.com/74011927/212407402-0bb49440-8d55-4494-b0ca-a9ef50daca20.png">
<img width="404" alt="image_4" src="https://user-images.githubusercontent.com/74011927/212407403-eeb05a8d-b12f-4c50-8a24-1883472d28e8.png">

**Comment by Vabene0312** [comment]
![16736402618452605512515361940025](https://user-images.githubusercontent.com/74011927/212409696-6f9e6cf6-4d5e-49fa-9270-cba69ab84b6a.jpg)
My launchpad lights this.

**Comment by mrharpo** [comment]
@Vabene0312 I've made some potential fixes on https://magnus.quaternion.media/

When you try them out, make sure to open the developer console and enable the `Disable cache` option (in the `Network` tab) while refreshing.

Also, if it still doesn't work, it would be helpful to expand the output of the console log where it says `connected`. Feel free to copy and paste the info here, as it's a little easier to read than a screenshot, but both are helpful!

Thanks again for taking the time to create an issue!

**Comment by Vabene0312** [comment]
Thanks for your help, now its works ;-)

**Comment by mrharpo** [comment]
Great! I'll push this change to launchchess.com

Thanks!

**Comment by Vabene0312** [comment]
I thank you for the quick answer and solution ;-)

**Comment by Vabene0312** [comment]
Maybe if you have time, and of course you want to, you could also do it so that the colors of the dolls can be customized. But of course this is just an assumption. And thanks for your work anyway

**Comment by mrharpo** [comment]
Yes, I have actually started developing this with #4, but haven't had the time to devote to any feature building as of late.

Feel free to give it a try if you like! 😉 The dev instructions in the readme should be up to date (and if they aren't, you can open a PR to fix them!).
