### ISSUE TITLE
Error: WebMidi must be enabled before adding event listeners.

### ISSUE THREAD

**Issue by subcontrabass** [quaternionmedia/LaunchChess#9]
Getting this error when trying to connect Launchpad X and Opera

![Screenshot from 2021-05-31 14-21-35](https://user-images.githubusercontent.com/3780772/120229639-8a972980-c21b-11eb-8704-7c4b901894cc.png)

**Comment by mrharpo** [comment]
Checked with latest code, and Opera is working as expected.
